import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // MD3 color tokens from design
        'surface-container-high': '#e2e7ff',
        'inverse-primary': '#b4c5ff',
        'surface': '#faf8ff',
        'surface-container': '#eaedff',
        'tertiary': '#632ecd',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-dim': '#d2d9f4',
        'on-secondary-fixed': '#002113',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#4edea3',
        'background': '#faf8ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#00174b',
        'secondary': '#006c49',
        'inverse-on-surface': '#eef0ff',
        'inverse-surface': '#283044',
        'surface-container-lowest': '#ffffff',
        'on-background': '#131b2e',
        'surface-container-highest': '#dae2fd',
        'on-tertiary-fixed': '#23005c',
        'on-primary': '#ffffff',
        'primary': '#004ac6',
        'primary-fixed-dim': '#b4c5ff',
        'on-surface-variant': '#434655',
        'surface-container-low': '#f2f3ff',
        'on-surface': '#131b2e',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#e9ddff',
        'on-primary-container': '#eeefff',
        'surface-tint': '#0053db',
        'outline-variant': '#c3c6d7',
        'on-tertiary-container': '#f6edff',
        'primary-fixed': '#dbe1ff',
        'surface-bright': '#faf8ff',
        'error': '#ba1a1a',
        'secondary-container': '#6cf8bb',
        'tertiary-container': '#7d4ce7',
        'outline': '#737686',
        'primary-container': '#2563eb',
        'surface-variant': '#dae2fd',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#6ffbbe',
        'on-tertiary-fixed-variant': '#5516be',
        'on-secondary-container': '#00714d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '24px',
        'container-max': '1440px',
        'sidebar-width': '280px',
        'margin-desktop': '32px',
        'stack-md': '16px',
        'stack-xs': '4px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-lg': '24px',
      },
      fontFamily: {
        'code-snippet': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'code-snippet': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        soft: '0 10px 30px rgba(15, 23, 42, 0.08)',
        sm: '0 1px 3px rgba(0,0,0,0.08)',
        lg: '0 4px 24px rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [],
} satisfies Config;
